### PR TITLE
Reduce minimal Python version and enable a plot to be embedded multiple times on the same page

### LINKED ISSUE #50: Support for Python 3.8
Thank you very much for this extension!
I wanted to ask if it would be possible to support Python 3.8 as well. I think many projects (including mine) are still stuck on older Python versions.

If I can be of help for this, please let me know!

### LINKED ISSUE #52: Plot can not be displayed multiple times on the same page
At the moment the same plot stored under the same "glue" name can not be displayed twice, as the renderer creates a div with `id=name` to render the plot into.
If that happens multiple times in the same page, the plot will be rendered multiple times into the same div.

A way around that is to assign a unique id to each div that is created.

I implemented that change in #51 and from my testing this seems to work well.

If you have time, I would appreciate if you could have a look and potentially upstream this change.

Thanks in advance!

### PR DESCRIPTION
**Pull request by AKuederle**
This would resolve #50 closes #52

### CODE REVIEW

**Comment by bryanwweber** [comment]
Thank you! Can you please:
1. Add Python 3.8 to the list of test runners in GitHub Actions?
2. Edit the line in the `docs/bokeh.ipynb` file where it says you can only glue a figure once in a page to be correct?

And you'll need to fix the tests. I believe you can do that by `tests/test_myst_nb_bokeh/test_bokeh_notebook.html` file, then running pytest (it will fail and should have a message that it generated a file), then commit the result.

**Comment by AKuederle** [comment]
> Also, are you interested in me giving you commit rights to this repo?

I think you should already be able to push to my repo (at least I ticked the "allow edits by maintainer" option when creating the PR)

**Comment by bryanwweber** [comment]
> I think you should already be able to push to my repo (at least I ticked the "allow edits by maintainer" option when creating the PR)

Yeah, that's fine. I don't plan to try to fix the test failures here, though 😄 I meant, do you want me to give you access to merge MRs on this "upstream" repository? You're clearly interested in the project overall, and it seems better to centralize the work rather than having forks with different functionality 😄

**Comment by AKuederle** [comment]
Mmh... I think fixing the test is a little more tricky as expected, as I am creating a random uuid. So the simple regression test doesn't work... I will think of something

**Comment by AKuederle** [comment]
> > I think you should already be able to push to my repo (at least I ticked the "allow edits by maintainer" option when creating the PR)
> 
> Yeah, that's fine. I don't plan to try to fix the test failures here, though smile I meant, do you want me to give you access to merge MRs on this "upstream" repository? You're clearly interested in the project overall, and it seems better to centralize the work rather than having forks with different functionality smile

Ah! Yes sure, if you want :) But no promises that I will do a lot of work beyond what I currently need.

**Comment by bryanwweber** [comment]
> Mmh... I think fixing the test is a little more tricky as expected, as I am creating a random uuid. So the simple regression test doesn't work... I will think of something

You can probably monkeypatch the uuid module (or the uuid4 class) to return the same string always in the tests. See here: https://docs.pytest.org/en/7.1.x/reference/reference.html#pytest.MonkeyPatch.setattr

**Comment by AKuederle** [comment]
@bryanwweber Can you have a final look?

**Review by bryanwweber — APPROVED** [review]

**Comment by bryanwweber** [comment]
Thank you!

**Pull request merged**
